.TH DMCRadio 1 "January 28, 2004" "DMCRadio 1.1.1"
.SH NAME
DMCRadio - console radio application
.SH SYNOPSIS
DMCRadio [options]
.SH DESCRIPTION
.PP
DMCRadio is a ncurses-based console program for radio tuner cards supported
by the Video4Linux system. It's like the 'radio' program by Gerd Knorr and Juli
Merino, but much better (I hope...). 
.br
It also features a recording function.
.SH OPTIONS
.TP
.B -h --help
Shows a small help and exits.
.TP
.B -m --mute
Mutes the radio and exits.
.TP
.B -r dev
.PD 0
.TP
.B --radiodev dev
Sets the radiodevice to dev. The default is /dev/radio.
.PD
.TP
.B -m dev
.PD 0
.TP
.B --mixerdev dev
Sets the mixerdevice to dev. The default is /dev/mixer.
.PD
.TP
.B -d dev
.PD 0
.TP
.B --dspdev dev
Sets the DSPdevice to dev. The default is /dev/dsp.
.br
(Used for recording.)
.PD
.TP
.B -v --version
Prints the version and exits.
.SH KEYBOARD CONTROLS
.TP
.B 1,2,3...9,0
jump to Preset Station 1 - 10
.TP
.B shift+[1,2,3...9,0]
jump to Preset Station 11 - 20
.TP
.B UP Key
.br
tune 0.05 MHz up
.TP
.B DOWN Key
tune 0.05 MHz down
.TP
.B LEFT Key
previous volumecontrol
.TP
.B RIGHT Key
next volumecontrol
.TP
.B >
increase volume
.TP
.B <
decrease volume
.TP
.B m
mute
.TP
.B d
denoiser (mutes radio "between" two stations)
.TP
.B l
show mixerlabels instead of names
.br
(e.g. "PhoneIn" instead of "phin")
.TP
.B g
go to a frequency
.TP
.B x
exit
.TP
.B ESC
.PD 0
.TP
.B q
.TP
.B e
mute and exit
.PD
.TP
.B f
runtime fontchanger
.IP
.B - UP Key
next font
.br
.B - DOWN Key
previous font
.TP
.B c
runtime colorchanger
.IP
.B - UP Key
next window
.br
.B - DOWN Key
previous window
.br
.B - f
cycle foreground color
.br
.B - b
cycle background color
.br
.B - o
toggle bold
.TP
.B r
record
.IP
.B - LEFT Key
previous volumecontrol
.br
.B - RIGHT Key
next volumecontrol
.br
.B - >
increase volume
.br
.B - <
decrease volume
.br
.B - a
auto-adjust (reduces volume on overruns)
.br
.B - SPACE
start/stop recording
.br
.B - n
next file
.br
    (same as typing space really really fast twice)
.br
.B - s
toggle mono/stereo
.br
.B - r
toggle between 11025Hz, 22050Hz and 44100Hz
.br
.B - m
change maximal filesize
.br
    (accepts values like "110.42MB", "1000" and "143kb")
.TP
.B i
show some details about your radio-card (or TV-card with radio-tuner)
.TP
.B +
switch to next helppage
.TP
.B -
switch to previous helppage
.SH DMCRADIORC
DMCRadio saves the current configuration to ~/.DMCRadiorc when exiting.
.PP
The format of this file is easy to understand. Lines starting with anything
that is not recognized will be ignored.
.PP
You can assign a value to a variable with
.br
.B Variable=Value
.br
The case of the variable-name will be ignored.
.PP
The config file is divided into four sections:
.TP
.B [Style]
# The font for the frequency-display
.br
.B LCDFont=small.raf
.br
# Appearence of the Tuner-window
.br
# (Can be set with 'c' in the program)
.br
# Bold means brighter foreground color
.br
.B Tunerfg=6
.br
.B Tunerbg=4
.br
.B Tunerbold=1
.br
# Same for:
.br
# Keys (Key Commands)
.br
# Stations (Preset Stations)
.br
# Status (Statusbar)
.br
# Info (Infos about your radio-card)
.br
# Scroll (The scroller)
.br
# Record (The record window)
.br
# Volume ("<" and ">" from the volume-control)
.TP
.B [Stations]
# On 89.0 MHz is a station called ...
.br
# (Up to 256 stations possible)
.br
.B 89.0=Radiostation whatever
.TP
.B [Buttons]
# Button 0 points to 89.0 MHz
.br
# If the frequency is used in the Stations section,
.br
# the name is shown in the Preset-Stations-window.
.br
# Otherwise the frequency is shown
.br
# (Up to 20 buttons are possible)
.br
.B 0=89.0
.TP
.B [Misc]
.br
# Specifies the radiodevice
.br
.B Radiodev=/dev/radio
.br
# Specifies the mixerdevice
.br
.B Mixerdev=/dev/mixer
.br
# Set the Audioinput to cd
.br
# (used for volume-control)
.br
.B Audioinput=cd
.br
# On startup, the tuner is set to 90.05.
.br
# If not given, the tuner is set to the
.br
# lowest frequency possible.
.br
# (On exit, the current frequency is saved here)
.br
.B Frequency=90.05
.br
# Mutes radio "between" two stations
.br
.B Denoiser=1
.br
# Maximal filesize for recording is 10485760 bytes (10MB)
.br
# Afer 10MB were written in one file, DMCRadio will continue
.br
# recording in a new file
.br
.B MaxRecSize=10485760
.br
.SH SEE ALSO
.BR radio(1)
.SH AUTHORS
.nf
DMCRadio was written by Sven Hesse (DrMcCoy).
